name: Build and Release

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'build-and-release'
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${{ matrix.rust }}
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup component add rustfmt
          rustup component add clippy
          rustup component add llvm-tools-preview
          rustup target add x86_64-pc-windows-gnu
          rustup target add x86_64-pc-windows-msvc
          rustup

      - name: Set up Rust (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${{ matrix.rust }}
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup component add rustfmt
          rustup component add clippy
          rustup component add llvm-tools-preview
          rustup target add x86_64-unknown-linux-gnu
          rustup

      - name: Set up Rust (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${{ matrix.rust }}
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup component add rustfmt
          rustup component add clippy
          rustup component add llvm-tools-preview
          rustup target add x86_64-apple-darwin
          rustup

      - name: Get app version
        id: get_version
        uses: dante-signal31/rust-app-version@v1.2.0
        with:
          cargo_toml_folder: './'

      - name: Build
        run: cargo build --release --target ${{ matrix.os }}

      - name: Create Release Text
        id: release-text
        run: |
          body="## Commits\n"
          body+=$(git log $(git describe --tags --always --abbrev=0)..HEAD --pretty=format:'\n- [`%h`](${{ github.server_url }}/${{ github.repository }}/commit/%H): %s (%an)') 
          echo -e $body >> release.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/gpt-commit-rust*
          tag_name: v${{ steps.get_version.outputs.app_version }}-${{ matrix.os }}
          body_path: release.md
